### ISSUE TITLE
Systemic with jest27 launches FSEVENTWRAP error

### ISSUE THREAD

**Issue by jgleal** [guidesmiths/systemic#50] opened 2021-11-08 15:31 UTC
With a basic systemic template, if you change mocha with jest (v27, with previous version it doesn't happen), jest launches this error:

![image](https://user-images.githubusercontent.com/2418727/140770120-59c1e35f-5ae4-49f7-91c9-3960f4845654.png)

Code to reproduce https://github.com/jgleal/systemic_jest27

**Comment by cressie176** [comment] 2021-11-08 22:47
Dupe of https://github.com/guidesmiths/confabulous/issues/11

**Closed by cressie176** 2021-11-08 22:47 UTC
